# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '回顾' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 回顾
pod 'Masonry'
pod 'BaiduMapKit'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'MBProgressHUD'

end
